services:
  mcp-manager:
    build: .
    container_name: mcp-manager
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge